### ISSUE TITLE
Migrate to SQLite (a.k.a Epic Rewrite)

### ISSUE THREAD

**Issue by wswld** [wswld/tray#27]
- [x] Implement migration/initialization algorithm
- [x] Initial migration

-----

Gonna start all over again. Gonna add SQLAlchemy and Click to the mix.

- [x] `models` file with SQLAlchemy (#34)
- [x] `api` file providing data endpoints to models
- [x] `cli` file providing Cli views based on `api` data 
- <del>`tray` script with Click (#32)</del>
- <del> 0.0.7 > 0.1.0 automatic data migration mechanism (#35)</del>
- [x] fix the error with migrations not being included on setup.

Perhaps we should perform migration on setup and create a mechanism to run migration manually, if for example the user deleted the `.tray` folder, but doesn't want to reinstall.

**Comment by wswld** [comment]
Closed #34 as models are done.
